udf: Verify symlink size before loading it
Fixes incorrect implementation in LineageOS 15.1 kernel leading to compilation errors. 
/home/herriemerim/LuneOS/zeus/webos-ports/tmp-glibc/work-shared/hammerhead/kernel-source/fs/udf/symlink.c: In function 'udf_symlink_filler':
/home/herriemerim/LuneOS/zeus/webos-ports/tmp-glibc/work-shared/hammerhead/kernel-source/fs/udf/symlink.c:125:3: error: label 'out_unlock_inode' used but not defined
  125 |   goto out_unlock_inode;

UDF specification allows arbitrarily large symlinks. However we support
only symlinks at most one block large. Check the length of the symlink
so that we don't access memory beyond end of the symlink block.

Reported-by: Carl Henrik Lunde <chlunde@gmail.com>
Signed-off-by: Jan Kara <jack@suse.cz>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>