bcmdhd: Disable debug flags
Since they cause headaches with newer GCC and Halium.

/home/herriemerim/LuneOS/zeus/webos-ports/tmp-glibc/work-shared/hammerhead/kernel-source/drivers/net/wireless/bcmdhd/bcmsdh_sdmmc_linux.c: In function 'bcmsdh_sdmmc_resume':
/home/herriemerim/LuneOS/zeus/webos-ports/tmp-glibc/work-shared/hammerhead/kernel-source/drivers/net/wireless/bcmdhd/bcmsdh_sdmmc_linux.c:244:11: error: implicit declaration of function 'check_wakeup_reason'; did you mean 'check_wakeup_irqs'? [-Werror=implicit-function-declaration]
  244 |  wakeup = check_wakeup_reason(bcmsdh_get_irq());

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>